# Generated by Django 3.2.12 on 2023-04-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lista', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_produto', models.CharField(max_length=100)),
            ],
        ),
    ]
