# Generated by Django 4.2 on 2023-04-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_produtos_name_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='name_produto',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
